FROM golang:alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/pong


FROM scratch

COPY --from=builder /go/bin/pong /go/bin/pong

EXPOSE 8080
ENV REQUEST_ORIGIN=http://localhost:8080

ENTRYPOINT ["/go/bin/pong"]